use_frameworks!

target 'Tor-Example' do
  platform :ios, '11.0'

  pod 'Tor/GeoIP', :path => '../' # :podspec => '../TorStatic.podspec'

  target 'Tor-Tests' do
    inherit! :search_paths
  end

end

target 'Tor-Example-Mac' do
  platform :macos, '10.13'

  pod 'Tor/GeoIP', :path => '../' # :podspec => '../TorStatic.podspec'
end
