use_frameworks!

def tor
  pod 'Tor/GeoIP',
    :path => '../'
#    :podspec => '../TorStatic.podspec'
end


target 'Tor-Example' do
  platform :ios, '12.0'

  tor

  target 'Tor-Tests' do
    inherit! :search_paths
  end

end

target 'Tor-Example-Mac' do
  platform :macos, '10.13'

  tor
end
